spring:
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${DISCORD_OAUTH_CLIENT_ID}
            client-secret: ${DISCORD_OAUTH_CLIENT_SECRET}
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope:
              - identify
              - email
              - guilds.join
            redirect-uri: "https://enigmamonitors.io/api/auth/guest/login/oauth2/code/discord"
            client-name: Enigma Monitors
        provider:
          discord:
            authorizationUri: https://discordapp.com/api/oauth2/authorize
            tokenUri: https://discordapp.com/api/oauth2/token
            userInfoUri: https://discordapp.com/api/users/@me
            usernameAttribute: id
  redis:
    url: ${REDIS_URL}
  session:
    store-type: redis

server:
  port: 8010
  servlet:
    session:
      cookie:
        name: U_SESSION
    context-path: /api/auth/

management:
  server:
    port: 9010
    base-path: /manage

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

security:
  jwt:
    header: Authorization
    prefix: Bearer
    expiration: ${SECURITY_JWT_EXPIRATION}
    secret: ${SECURITY_JWT_SECRET}
  url:
    login: https://enigmamonitors.io
    logout: https://enigmamonitors.io/authorization

discord:
  bot:
    token: ${DISCORD_BOT_TOKEN}
  trusted-guild: 688446328761614440