spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: auth-service
      auto-index-creation: true
  session:
    store-type: mongodb
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: 767419431357382656
            client-secret: ENj1A0vJYcDHrRqiLO8N4mb4UiRuplHz
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope:
              - identify
              - email
              - guilds.join
            redirect-uri: "http://localhost:8010/api/auth/guests/login/oauth2/code/discord"
            client-name: Enigma Solutions
        provider:
          discord:
            authorizationUri: https://discordapp.com/api/oauth2/authorize
            tokenUri: https://discordapp.com/api/oauth2/token
            userInfoUri: https://discordapp.com/api/users/@me
            usernameAttribute: id

server:
  error:
    include-stacktrace: always
  port: 8010
  servlet:
    session:
      cookie:
        name: U_SESSION
    context-path: /api/auth/

management:
  server:
    port: 9010
    base-path: /manage

security:
  jwt:
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: jwt-secret
  url:
    login: http://localhost:3000
    logout: http://localhost:3000/authorization

discord:
  bot:
    token: Bot NzY3NDE5NDMxMzU3MzgyNjU2.X4xpCg.TTHtJEwsTv8ZlKQjJUVRFt1zBHI

dictionary-service:
  url: http://localhost:8015/dictionary
