pipelines:
  pull-requests:
    '**':
      - step:
          name: Build and Test
          image: gradle:7.1-jdk11
          caches:
            - gradle
          script:
            - gradle clean build
  custom:
    auth-service:
      - step:
          name: Build Auth Service
          image: gradle:7.1-jdk11
          caches:
            - gradle
          script:
            - gradle clean build -p auth-service
          artifacts:
            - auth-service/build/*
      - step:
          name: Push Docker Image
          image: atlassian/pipelines-awscli
          services:
            - docker
          caches:
            - docker
          script:
            - cd auth-service
            # Login to docker registry on AWS
            - eval $(aws ecr get-login --no-include-email)
            # Build image
            - docker build -t $DOCKER_IMAGE_URL:$BITBUCKET_BUILD_NUMBER -t $DOCKER_IMAGE_URL:latest .
            # Push image to private registry
            - docker push $DOCKER_IMAGE_URL
      - step:
          name: Deploy to AWS
          trigger: manual
          script:
            - pipe: atlassian/aws-ecs-deploy:1.5.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                CLUSTER_NAME: 'web-monitor'
                SERVICE_NAME: 'auth-service'
                FORCE_NEW_DEPLOYMENT: 'true'