pipelines:
  pull-requests:
    '**':
      - step:
          name: Build and Test
          image: gradle:7.1.1-jdk-11
          caches:
            - gradle
          script:
            - gradle clean build -x test