spring:
  application:
    name: web-broadcast-service

server:
  error:
    include-stacktrace: always
  port: ${SERVER_PORT:8020}

management:
  server:
    port: ${MANAGE_PORT:9020}
    base-path: /manage

security:
  jwt:
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: ${JWT_SECRET_KEY:jwt-secret}

kafka:
  bootstrap-servers: localhost:9092
  tweet-consumer:
    group-id: web-broadcast-tweet-group
    topic: twitter-tweet-broadcast-base
  recognition-consumer:
    group-id: web-broadcast-recognition-group
    topic: twitter-tweet-recognition-broadcast
  staff-consumer:
    group-id: web-broadcast-staff-group
    topic: staff-broadcast

broadcast:
  history-limit: 25