server:
  port: 8020

management:
  server:
    port: 9020
    base-path: /manage

security:
  jwt:
    query-param: token
    secret: ${SECURITY_JWT_SECRET}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  tweet-consumer:
    topic: twitter-tweet-broadcast-base
  recognition-consumer:
    topic: twitter-tweet-recognition-broadcast-base
  staff-consumer:
    topic: twitter-staff-broadcast
