server:
  port: 8020

management:
  server:
    port: 9020
    base-path: /manage

security:
  jwt:
    header: Authorization
    prefix: Bearer
    expiration: ${SECURITY_JWT_EXPIRATION}
    secret: ${SECURITY_JWT_SECRET}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  tweet-consumer:
    group-id: web-broadcast-tweet-group
    topic: twitter-tweet-broadcast-base
  recognition-consumer:
    group-id: web-broadcast-recognition-group
    topic: twitter-tweet-recognition-broadcast-base
  staff-consumer:
    group-id: web-broadcast-staff-group
    topic: twitter-staff-broadcast

broadcast:
  history-limit: ${BROADCAST_HISTORY_LIMIT}