server:
  error:
    include-stacktrace: always
  port: 8020

management:
  server:
    port: 9020
    base-path: /manage

security:
  jwt:
    query-param: token
    secret: jwt-secret

kafka:
  bootstrap-servers: localhost:9092
  tweet-consumer:
    topic: twitter-tweet-broadcast-base
  recognition-consumer:
    topic: twitter-tweet-recognition-broadcast-base
  staff-consumer:
    topic: twitter-staff-broadcast
