spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: dictionary-service
  webflux:
    base-path: /api/dictionary

server:
  port: 8015

management:
  server:
    port: 9015
    base-path: /manage
