server:
  port: 8025

discord:
  token: ${DISCORD_BOT_TOKEN}

dictionary-service:
  url: ${DICTIONARY_SERVICE_URL}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  producer:
    twitter-staff-broadcast: twitter-staff-broadcast
    header: Customer-Id