server:
  port : 8081

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://admin:ZRgCRWfi3M76p8yo@socialmonitors.kwvqy.mongodb.net/advanced-private-monitor}

alert:
  discord:
    url: ${ALERT_DISCORD_URL:https://discord.com/api/webhooks/830449746653085707/na-oTYH5X5wL8WABdJO4uHUsD8y4jTnIj8xvBiH3x9xfmtzVq8yXY_6NjqoIWJLITIrR}

discord:
  embed:
    color:
      retweet: 15922277
      tweet: 5814783
      reply: 3460243
      alert: 16023551

kafka:
  bootstrap-servers: localhost:9092
  tweet-consumer:
    group-id: discord-broadcast-tweet
    topic: twitter-tweet-broadcast
  alert-consumer:
    group-id: discord-broadcast-alert
    topic: twitter-alert-broadcast