spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

alert:
  discord:
    url: ${ALERT_DISCORD_URL}

discord:
  embed:
    color:
      retweet: 15922277
      tweet: 5814783
      reply: 3460243
      alert: 16023551