spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: discord-broadcast-service

server:
  port: 9085

dictionary-service:
  url: ${DICTIONARY_SERVICE_URL}

alert:
  discord:
    url: ${ALERT_DISCORD_URL}

discord:
  role:
    monitor-team: 901167071793135697
  embed:
    color:
      retweet: 15922277
      tweet: 5814783
      reply: 3460243
      alert: 16023551
      user-updates: 13664492

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  tweet-consumer-base:
    group-id: discord-broadcast-tweet-base-group
    topic: twitter-tweet-broadcast-base
  tweet-consumer-live-release:
    group-id: discord-broadcast-tweet-live-release-group
    topic: twitter-tweet-broadcast-live-release
  recognition-consumer-base:
    group-id: discord-broadcast-recognition-base-group
    topic: twitter-tweet-recognition-broadcast-base
  recognition-consumer-live-release:
    group-id: discord-broadcast-recognition-live-release-group
    topic: twitter-tweet-recognition-broadcast-live-release
  alert-consumer:
    group-id: discord-broadcast-alert-group
    topic: twitter-monitor-alert-broadcast
  user-updates-consumer-base:
    group-id: discord-broadcast-user-updates-base-group
    topic: twitter-user-updates-broadcast-base
  user-updates-consumer-live-release:
    group-id: discord-broadcast-user-updates-live-release-group
    topic: twitter-user-updates-broadcast-live-release

