spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: discord-broadcast-service

server:
  port: 8045

alert:
  discord:
    url: https://discord.com/api/webhooks/830449746653085707/na-oTYH5X5wL8WABdJO4uHUsD8y4jTnIj8xvBiH3x9xfmtzVq8yXY_6NjqoIWJLITIrR

discord:
  role:
    monitor-team: 901167071793135697
  embed:
    color:
      retweet: 15922277
      tweet: 5814783
      reply: 3460243
      alert: 16023551
      user-updates: 13664492

dictionary-service:
  url: http://localhost:8015/api/dictionary

kafka:
  bootstrap-servers: localhost:9092
  tweet-consumer-base:
    group-id: discord-broadcast-tweet-base-group
    topic: twitter-tweet-broadcast-base
  tweet-consumer-live-release:
    group-id: discord-broadcast-tweet-live-release-group
    topic: twitter-tweet-broadcast-live-release
  recognition-consumer-base:
    group-id: discord-broadcast-recognition-base-group
    topic: twitter-tweet-recognition-broadcast-base
  recognition-consumer-live=release:
    group-id: discord-broadcast-recognition-live-release-group
    topic: twitter-tweet-recognition-broadcast-live-release
  alert-consumer:
    group-id: discord-broadcast-alert-group
    topic: twitter-monitor-alert-broadcast
  user-updates-consumer-base:
    group-id: discord-broadcast-user-updates-base-group
    topic: twitter-user-updates-broadcast-base
  user-updates-consumer-live-release:
    group-id: discord-broadcast-user-updates-live-release-group
    topic: twitter-user-updates-broadcast-live-release
