server:
  port: 8085

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: discord-broadcast-service
  main:
    web-application-type: none

alert:
  discord:
    url: ${ALERT_DISCORD_URL}

discord:
  embed:
    color:
      retweet: 15922277
      tweet: 5814783
      reply: 3460243
      alert: 16023551

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  tweet-consumer-base:
    group-id: discord-broadcast-tweet-base-group
    topic: twitter-tweet-broadcast-base
  tweet-consumer-live-release:
    group-id: discord-broadcast-tweet-live-release-group
    topic: twitter-tweet-broadcast-live-release
  recognition-consumer-base:
    group-id: discord-broadcast-recognition-base-group
    topic: twitter-tweet-recognition-broadcast-base
  recognition-consumer-live=release:
    group-id: discord-broadcast-recognition-live-release-group
    topic: twitter-tweet-recognition-broadcast-live-release
  alert-consumer:
    group-id: discord-broadcast-alert-group
    topic: twitter-monitor-alert-broadcast