server:
  port: 8030
  servlet:
    context-path: /twitter-monitor

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: twitter-monitor
  security:
    user:
      name: admin
      password: password

kafka:
  bootstrap-servers: localhost:9092
  producer:
    tweet-base-topic: twitter-tweet-broadcast-base
    tweet-live-release-topic: twitter-tweet-broadcast-live-release
    tweet-recognition-base-topic: twitter-tweet-recognition-broadcast-base
    tweet-recognition-live-release-topic: twitter-tweet-recognition-broadcast-live-release
    user-updates-base-topic: twitter-user-updates-broadcast-base
    user-updates-live-release-topic: twitter-user-updates-broadcast-live-release
    twitter-monitor-alert-topic: twitter-monitor-alert-broadcast

dictionary-service:
  url: http://localhost:8015/api/dictionary

aws:
  rekognition:
    access-key: AKIAZCHZYD2SJULQYADP
    secret-key: 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

pastebin:
  developer-key: HQ_O6vDxEYArhfwUWEWVJYrihA_Cv839
