spring:
    data:
        mongodb:
          uri: ${MONGODB_URI:mongodb+srv://admin:ZRgCRWfi3M76p8yo@socialmonitors.kwvqy.mongodb.net/advanced-private-monitor}

kafka:
  bootstrap-servers: localhost:9092
  tweet-consumer-base:
    group-id: discord-broadcast-tweet
    topic: twitter-tweet-broadcast
  tweet-consumer-live-release:
    group-id: discord-broadcast-tweet
    topic: twitter-tweet-broadcast-live-release
  alert-consumer:
    group-id: discord-broadcast-alert
    topic: twitter-alert-broadcast

monitor:
  home-timeline:
    delay: 4025
    count: 1
  user-timeline:
    delay: 700
    count: 1