server:
  port: 8030
  servlet:
    context-path: /twitter-monitor

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: twitter-monitor
  security:
    user:
      name: ${MONITOR_USER_NAME}
      password: ${MONITOR_USER_PASSWORD}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  producer:
    tweet-base-topic: twitter-tweet-broadcast-base
    tweet-live-release-topic: twitter-tweet-broadcast-live-release
    tweet-recognition-base-topic: twitter-tweet-recognition-broadcast-base
    tweet-recognition-live-release-topic: twitter-tweet-recognition-broadcast-live-release
    user-updates-base-topic: twitter-user-updates-broadcast-base
    user-updates-live-release-topic: twitter-user-updates-broadcast-live-release
    twitter-monitor-alert-topic: twitter-monitor-alert-broadcast

dictionary-service:
  url: ${DICTIONARY_SERVICE_URL}

discord-broadcast-service:
  url: ${DISCORD_BROADCAST_SERVICE_URL}

aws:
  rekognition:
    access-key: AKIAZCHZYD2SJULQYADP
    secret-key: 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

pastebin:
  developer-key: HQ_O6vDxEYArhfwUWEWVJYrihA_Cv839